name:                archivist
version:             0.0.0.0
github:              "NorfairKing/archivist"
license:             MIT

library:
  source-dirs: src
  dependencies:
  - async
  - base >= 4.7 && < 5
  - brick
  - bytestring
  - cursor
  - cursor-brick
  - directory
  - microlens
  - path
  - path-io
  - text
  - typed-process
  - vty

executables:
  archivist:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - archivist
